### ISSUE TITLE
radvel mcmc not working with numpy>=1.22

### ISSUE THREAD

**Issue by skyientist** [California-Planet-Search/radvel#364]
I updated numpy to version 1.22.2 and I keep getting 'numpy.__config__' has no attribute 'blas_opt_info'. I had to downgrade to numpy 1.21.3 to get radvel mcmc to work.

**Comment by sblunt** [comment]
Hey sorry for the delayed reply on this. I'm going to remove the piece of code that does this check in a forthcoming release. In the meantime, you can comment out lines 267-275 in mcmc.py. Stay tuned for a more complete solution in next version.

**Comment by bjfultn** [comment]
will be fixed in 1.4.11
